### ISSUE TITLE
Login or Register API through OTP

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/user-service#71]
## Description

User Journey
1. If the user is not registered - register a user and log them in.
2. If the user is registered - log in a user.

Endpoing - `/login/otp`

```json
{
	"loginId": <phone number>,
	"password": <OTP>,
	"applicationId": <appId>
}
```

### Internal Implementation
Reset the pass to `salt` + OTP. Update the password every login.

**Comment by choxx** [comment]
Fixed  with PR #72 & #73
